SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.tblSoGVCNSoKetHKI', 'U') IS NULL
BEGIN
	CREATE TABLE dbo.tblSoGVCNSoKetHKI
	(
		SoKetHKIID int IDENTITY(1,1) NOT NULL
			CONSTRAINT PK_tblSoGVCNSoKetHKI PRIMARY KEY,
		SoGVCNID int NOT NULL,
		JsonData nvarchar(max) NOT NULL,
		Enable bit NOT NULL
			CONSTRAINT DF_tblSoGVCNSoKetHKI_Enable DEFAULT (1),
		CreateUser varchar(9) NULL,
		CreateTime datetime NOT NULL
			CONSTRAINT DF_tblSoGVCNSoKetHKI_CreateTime DEFAULT (GETDATE()),
		UpdateUser varchar(9) NULL,
		UpdateTime datetime NOT NULL
			CONSTRAINT DF_tblSoGVCNSoKetHKI_UpdateTime DEFAULT (GETDATE()),
		CONSTRAINT FK_tblSoGVCNSoKetHKI_SoGVCN
			FOREIGN KEY (SoGVCNID) REFERENCES dbo.tblSoGVCN(SoGVCNID),
		CONSTRAINT CK_tblSoGVCNSoKetHKI_JsonData
			CHECK (ISJSON(JsonData) = 1)
	);

	CREATE UNIQUE INDEX UX_tblSoGVCNSoKetHKI_SoGVCNID
		ON dbo.tblSoGVCNSoKetHKI(SoGVCNID);
END;

COMMIT TRANSACTION;
