const messages = {
    vi: {
        "badge": "Badge",
        "open": "Open",
        "close": "Close",
        "dismiss": "Dismiss",
        "confirmEdit": {
            "ok": "OK",
            "cancel": "Cancel"
        },
        "dataIterator": {
            "noResultsText": "No matching records found",
            "loadingText": "Loading items..."
        },
        "dataTable": {
            "itemsPerPageText": "Rows per page:",
            "ariaLabel": {
                "sortDescending": "Sorted descending.",
                "sortAscending": "Sorted ascending.",
                "sortNone": "Not sorted.",
                "activateNone": "Activate to remove sorting.",
                "activateDescending": "Activate to sort descending.",
                "activateAscending": "Activate to sort ascending."
            },
            "sortBy": "Sort by"
        },
        "dataFooter": {
            "itemsPerPageText": "Items per page:",
            "itemsPerPageAll": "All",
            "nextPage": "Next page",
            "prevPage": "Previous page",
            "firstPage": "First page",
            "lastPage": "Last page",
            "pageText": "{0}-{1} of {2}"
        },
        "dateRangeInput": {
            "divider": "to"
        },
        "datePicker": {
            "itemsSelected": "{0} selected",
            "range": {
                "title": "Select dates",
                "header": "Enter dates"
            },
            "title": "Select date",
            "header": "Enter date",
            "input": {
                "placeholder": "Enter date"
            }
        },
        "noDataText": "No data available",
        "carousel": {
            "prev": "Previous visual",
            "next": "Next visual",
            "ariaLabel": {
                "delimiter": "Carousel slide {0} of {1}"
            }
        },
        "calendar": {
            "moreEvents": "{0} more",
            "today": "Today"
        },
        "input": {
            "clear": "Clear {0}",
            "prependAction": "{0} prepended action",
            "appendAction": "{0} appended action",
            "otp": "Please enter OTP character {0}"
        },
        "fileInput": {
            "counter": "{0} files",
            "counterSize": "{0} files ({1} in total)"
        },
        "timePicker": {
            "am": "AM",
            "pm": "PM",
            "title": "Select Time"
        },
        "pagination": {
            "ariaLabel": {
                "root": "Pagination Navigation",
                "next": "Next page",
                "previous": "Previous page",
                "page": "Go to page {0}",
                "currentPage": "Page {0}, Current page",
                "first": "First page",
                "last": "Last page"
            }
        },
        "stepper": {
            "next": "Next",
            "prev": "Previous"
        },
        "rating": {
            "ariaLabel": {
                "item": "Rating {0} of {1}"
            }
        },
        "loading": "Loading...",
        "infiniteScroll": {
            "loadMore": "Load more",
            "empty": "No more"
        }
    }
}
$('document').ready(() => {
    // app.component(Toasted)
    const i18n = VueI18n.createI18n({
        legacy: false,
        locale: 'vi',
        fallbackLocale: 'en',
        messages: {
            en: {
                message: {
                    nameProject: "Report on learning outcomes",
                    language: 'English',
                    studyResult: 'STUDY RESULT',
                    selectedStudent: 'Selected student',
                    grade: "Grade",
                    class: "Class",
                    parent: "Parent",
                    Skill_Knowledge: 'SKILL - KNOWLEDGE',
                    Common_Ability: 'COMMON ABILITY',
                    Quality: 'QUALITY',
                    Personal_Ability: 'PERSONAL ABILITY',

                    evaluation: "Evaluation",
                    comment: "Comment",

                    studentList: "Student list",

                    selectLanguage: "Select Language",
                    vietNam: "Vietnam",
                    english: "English",
                    next: "Next",
                    back: "Back",
                    confirm: "Confirm",
                    close: "Close",

                    parent: "Parent",

                    listTheme: "List Theme",

                    monthList: "Month list",
                    studentNotFound: "Student not found",
                    month: "Month",
                    semester: "Semester",
                    selectSemester: "Select Semester",

                    rating: "Rating",
                    averageScore: "Average score",
                    comment: "Advise of parents",
                    commentNotFound: "No comments yet",

                    announced: "Viewed", //"Announced",
                    notYetAnnounced: "Not yet Viewed",

                    totalResults: "Total results",

                    ProgressBaseEnglish: "Progress-based English proficiency test results",

                    ActivitiesAssessment: "Activities assessment",

                    Notes: "Notes",
                    NotMeetingRequirements: "Not meeting requirements",
                    MeetingRequirements: "Meeting requirements",
                    ExceedingRequirements: "Exceeding requirements",
                    NotImplementingWithoutSpecificReasons: "Not implementing without specific reasons",
                    PointsTotalSkill: "Points per skill and total points of skills",

                    Score: "Score",
                    points: "points",
                    PathwaysTestResults_C3: "Pathways test results",
                    IELTSEquivalent: "IELTS Equivalent",
                    Result: "Periodic test results",

                    midSesemter: "Mid Sesemter",
                    finalSesemter: "Final Sesemter",

                    allYear: "All Year",
                    AveragePoints: "Average Points",
                    MidtermPoints: "Mid-term Points",
                    FinalPoints: "Final Points",
                    RegularTest: "Regular Test",
                    TotalPoints: "Total points",

                    //Module Giao bài
                    Setting: "Setting",
                    ControlPanel: "Control Panel",
                    MyDocument: "My Document",
                    Subject: "Subject",
                    AssignmentsToGrade: "Assignments",
                    NoAssignmentToGrade: "Not found data!",
                    CreateContent: "Create Content",
                    ClassNotAssigned: "This class hasn’t been assigned any assignments yet.",
                    ContactDev: "Please contact the development team for more information!",
                    NotFoundSubject: "Your subject could not be found",
                    ClassSize: "Class Size",
                    Students: "students",
                    EmptyLessonAndAssignment: "No lessons or assignments available",
                    GradeNow: "Grade Now",
                    Submitted: "Submitted",
                    NotSubmitted: "Not Submitted",
                    DraftGrading: "Draft Grading",
                    DoingAssignment: "Doing Assignment",
                    ResubmissionRequested: "Resubmission Requested",
                    Graded: "Graded",
                    DueDate: "Due Date",
                    ViewGradebook: "View Gradebook",
                    NeedGrade: "Need Grade",
                    ReviewGraded: "Review Graded",
                    Completed: "Completed",
                    InProgress: "In Progress",
                    ViewProgress: "View Progress",
                    ASSIGNMENT: "ASSIGNMENT",
                    Assignment: "Assignment",
                    LESSON: "LESSON",
                    Chapter: "Chapter",
                    Grade: "Grade",
                    ContentLibrary: 'Content Library',
                    ListSubjects: "List Subjects",
                    ViewDetail: "View Detail",
                    Delete: "Delete",
                    Instructions: "Instructions",
                    Decriptions: "Decriptions",
                    Create: "Create",
                    Close: "Close",
                    ChooseWeek: "Select Week",
                    Title: "Title",
                    ChooseContent: "Select Content",
                    ListClassAssigned: "Classes Assigned",
                    Update: "Update",
                    EditContent: "Edit content",
                    TotalScore: "Total score",
                    Assigned: "Assign assignment",
                    SaveAssignment: "Save assignment",
                    AssignAssignment: "Assign assignment",
                    Time: "Time",
                    ChooseClassToAssign: "Choose class to assign",
                    ChooseStudentToAssign: "Choose student to assign",
                    SelectAll: "Select all",
                    Selected: "Selected",
                    ExpirationDate: "Expiration date",
                    ExpirationTime: "Expiration time",
                    AddNewSection: "Add new section",
                    DragOrSelectAComponentFromTheLibraryToGetStarted: "Drag or select a component from the library to get started",
                    DropQuestionHere: "Drop your question here",
                    Question: "Question",
                    Total: "Total",
                    NoAnswer: "No answer",
                    QuestionLibrary: "Question library",
                    InteractiveQuiz: "Interactive quiz (Quiz)",
                    EssayAndPracticeQuestions: "Essay & Practice Questions",
                    Preview: "Preview",
                    SortNumber: "Sort number",
                    Attribute: "Attribute",
                    GradingMethod: "Grading method",
                    QuestionContent: "Question content",
                    Answer: "Answer",
                    Advanced: "Advanced",
                    MoreAnswer: "More answer",
                    Correct: "Correct",
                    Incorrect: "Incorrect",
                    Structure: "Structure: [Text] [Blank 1] [Text]...",
                    TextContent: "Text content",
                    CorrectAnswer: "Correct answer",
                    AddText: "Add Text",
                    AddBlank: "Add Blank",
                    Column: "Column",
                    Similar: "Similar",
                    AddPair: "Add pair",
                    NoAnswerConfig: "This question type has no answer configuration. Scores will be graded manually",
                    MaxCharacters: "Max characters",
                    Step: "Step",
                    PasteQuestionJSON: "Paste Question JSON",
                    PasteQuestionJSONIn: "Paste Question JSON in here...",
                    ViewSampleJSON: "View Sample JSON Format",
                    JSONError: "JSON Error",
                    ValidJSON: "Valid JSON",
                    Found: "Found",
                    PreviewResult: "Preview result",
                    Valid: "Valid",
                    Error: "Error",
                    DeleteAll: "Delete all",
                    Cancel: "Cancel",
                    Explanation: "Explanation",

                    // 
                    Statistics: "Statistics",
                    LimitAssigned: "Limit Assigned",
                    OnScaleOf: "On a scale of",
                    Refresh: "Refresh",
                    ViewClassReport: "View Class Report",
                    GradeAllAssignments: "Grade All Assignments",
                    FindStudent: "Find Student",
                    GradeAssignment: "Grade Assignment",
                    Actions: "Actions",
                    NoticeHighestScoreSubmission: "Note: The system records the submission with the highest score",
                    PleaseSelectClassSubjectAssignment: "Please select Class, Subject, and Assignment to view data.",
                    MaximumScore: "Maximum Score",
                    SubmissionNumber: "Submission Number",
                    Status: "Status",
                    SubmissionTime: "Submission Time",
                    Attempt: "Attempt",
                    PleaseSelectAssignment: "Please select an assignment",
                    StudentID: "Student ID",
                    RegistrationNumber: "Registration Number",
                    StudentName: "Student Name",
                    SubmissionInfo: "Submission Information",
                    SectionGroupName: "Section/Group Name",
                    ShuffleQuestions: "Shuffle Questions",
                    ShuffleAnswers: "Shuffle Answers",
                    SectionDescription: "Description/Instructions for this Section",
                    ShowAllQuestionsInGroup: "Show All Questions in Group",
                    EnterQuestion: "Enter a Question...",
                    SelectSectionOrQuestionToEdit: "Select a section or question to edit.",
                    AssignmentStructure: "Assignment Structure",
                    GradingProgress: "Grading Progress",
                    SummaryAndGeneralComments: "Summary & General Comments",
                    FinalScore: "Final Score",
                    OverallComment: "Overall Comment for the Entire Assignment",
                    EnterGeneralFeedback: "Enter general feedback about the student's work...",
                    PathNotFound: "Path not found",
                    TeacherCommentOptional: "Teacher's Comment (optional)",

                    // Soạn bài học
                    SaveDraft: "Save draft",
                    SaveAndPublish: "Save and publish",
                    SaveAndAssign: "Save and assign",
                    PleaseEnterDateTime: "Please enter date and time",
                    PleaseSelectAtLeastOneClass: "Please select at least one class to assign!",
                    SaveAndAssignSuccess: "Saved and assigned successfully!",
                    ClassList: "Class list",
                    StartAddingContent: "Start adding content to your lesson from the library on the left.",
                    NoVideo: "No video",
                    TextBlock: "Text block",
                    Image: "Image",
                    Attachment: "Attachment",
                    UnknownComponent: "Unknown component",
                    TextTitle: "Text title",
                    NewTextContent: "New text content",
                    ImageTitle: "Image title",
                    YoutubeTitle: "YouTube title",
                    FileTitle: "File title",
                    Audio: "Audio (Record/Upload)",
                    AudioTitle: "Audio title",
                    HtmlTitle: "HTML title",
                    GeneralInfo: "General information",
                    Content: "Content",
                    LessonTitle: "Lesson title",
                    DescriptionGuide: "Description / Instruction",
                    Week: "Week",
                    WeekExample: "Example: Week 5, Review",
                    ChapterTopic: "Chapter / Topic",
                    ChapterExample: "Example: Chapter 1: Exponents",
                    SelectComponentToEdit: "Select a component to edit.",
                    BlockTitleOptional: "Content block title (Optional)",
                    EditText: "Edit text",
                    UploadImage: "Upload image",
                    Caption: "Caption",
                    PasteVideoLink: "Paste video or YouTube link...",
                    VideoNote: "*Note: Uploaded video must be under 15 minutes and filename must not exceed 100 characters",
                    RecordOrUploadAudio: "Record or upload audio",
                    ImportFromLibrary: "Import from learning materials library",
                    PasteHTML: "Enter/Paste HTML...",
                    AnswerConfig: "Answer configuration:",
                    AdvancedAnswerSettings: "Advanced answer settings",
                    QuestionContentLabel: "Question content:",
                    AddOption: "Add option",
                    Structure: "Structure: [Text] [Blank 1] [Text]...",
                    ColumnA: "Column A",
                    ColumnB: "Column B (matching)",
                    LoadingData: "Loading data...",
                    ContinuingUpload: "Continuing upload...",
                    Uploading: "Uploading...",
                    UpdatingVideoPlaylist: "Updating video into playlist....",
                    WaitingYoutube: "Waiting for YouTube processing (may take 2 - 5 minutes)...",
                    VideoStatusError: "Error checking video processing status",
                    VideoTooLongWarning: "Video may be too long (upload < 15 minutes only)",
                    SearchingFolder: "Searching for folder...",
                    GrantingFilePermission: "Granting file permission...",
                    NewOption: "New option",
                    UploadFile: "Upload file",
                    UploadVideo: "Upload video",
                    ImportDigitalLesson: "Import lesson from digital materials",
                    ContentList: "Content list",
                    ContentName: "Content name",
                    ContentType: "Content type",
                    Actions: "Actions",
                    Thumbnail: "Thumbnail",
                    MaterialName: "Material name",
                    PreviewLesson: "Preview lesson",
                    ClickTo: "Click",
                    EditContentShort: "to edit content",
                    ContentHtmlLatex: "Content (supports HTML and LaTeX)",
                    NoContent: "No content...",
                    Save: "Save",
                    LoadingGradebookData: "Loading gradebook data...",
                    ClassGradebook: "Class gradebook",
                    FullName: "Full name",
                    Maximum: "Maximum",
                    SelectClassSubjectNotice: "Please select Class and Subject to view data.",
                    ClassAverageScore: "Class average score",
                    PublicContentLibrary: "Public content library",
                    Lesson: "Lesson",
                    RetrieveContent: "Retrieve content",
                    ContentRetrieved: "Content retrieved",
                    NotRetrieved: "Not retrieved",
                    Creator: "Creator",
                    PreviewContent: "Preview content",
                    PreviewDraftLesson: "Preview draft lesson",
                    RetrievedSuccess: "Content retrieved successfully!",
                    Statistical: "Statistical",
                    HomeworkGiver: "Homework giver",
                    Classname: "Classname"
                }
            },
            vi: {
                message: {
                    nameProject: "Báo cáo kết quả học tập",
                    language: 'Tiếng Việt',
                    studyResult: 'KẾT QUẢ HỌC TẬP',
                    selectedStudent: 'Học sinh đang chọn',
                    grade: "Khối",
                    class: "Lớp",
                    parent: "Phụ huynh",
                    Skill_Knowledge: 'KIẾN THỨC - KĨ NĂNG',
                    Common_Ability: 'NĂNG LỰC CHUNG',
                    Quality: 'PHẨM CHẤT',
                    Personal_Ability: 'NĂNG LỰC RIÊNG',
                    evaluation: "Nội dung đánh giá",
                    comment: "Ý kiến của phụ huynh",

                    studentList: "Danh sách học sinh",

                    selectLanguage: "Chọn ngôn ngữ",
                    vietNam: "Việt Nam",
                    english: "Tiếng Anh",
                    next: "Tiếp tục",
                    back: "Trở về",
                    confirm: "Xác nhận",
                    close: "Đóng",

                    parent: "Phụ huynh",

                    listTheme: "Danh sách chủ đề",

                    monthList: "Danh sách tháng",
                    studentNotFound: "Không tìm thấy học sinh",
                    month: "Tháng",
                    semester: "Học kì",
                    selectSemester: "Chọn học kì",

                    rating: "Xếp loại",
                    averageScore: "Điểm trung bình",
                    commentNotFound: "Chưa có nhận xét",

                    announced: "Đã xem",
                    notYetAnnounced: "Chưa xem",

                    totalResults: "Tổng điểm",
                    ProgressBaseEnglish: "Kết quả kiểm tra năng lực tiếng Anh theo Lộ trình Cambridge",
                    ActivitiesAssessment: "Kết quả các hoạt động rèn luyện",
                    Notes: "Ghi chú",
                    NotMeetingRequirements: "Chưa đạt yêu cầu",
                    MeetingRequirements: "Đạt yêu cầu",
                    ExceedingRequirements: "Vượt yêu cầu",
                    NotImplementingWithoutSpecificReasons: "Không thực hiện",
                    PointsTotalSkill: "Điểm mỗi kĩ năng và tổng điểm các kĩ năng",

                    Score: "Điểm",
                    points: "điểm",
                    PathwaysTestResults_C3: "Kết quả đánh giá Tiếng Anh Cambridge theo lộ trình",
                    IELTSEquivalent: "Quy đổi điểm IELTS",
                    Result: "Kết quả kiểm tra định kì",
                    midSesemter: "Giữa kì",
                    finalSesemter: "Cuối kì",
                    allYear: "Cả năm",
                    AveragePoints: "Điểm TB",
                    MidtermPoints: "Điểm GK",
                    FinalPoints: "Điểm cuối kì",
                    RegularTest: "Điểm Thường xuyên",
                    TotalPoints: "Điểm tổng",

                    //Module Giao bài
                    Setting: "Cấu hình",
                    ControlPanel: "Bảng điều khiển",
                    MyDocument: "Tài liệu của tôi",
                    Subject: "Môn học",
                    AssignmentsToGrade: "Bài tập",
                    NoAssignmentToGrade: "Không tìm thấy bài tập!",
                    CreateContent: "Tạo nội dung",
                    ClassNotAssigned: "Lớp này chưa được giao bài tập nào.",
                    ContactDev: "Thầy/ cô hãy liên hệ bộ phận phát triển để tìm hiểu thêm thông tin!",
                    NotFoundSubject: "Không tìm thấy môn học của thầy/cô",
                    ClassSize: "Sĩ số",
                    Students: "học sinh",
                    EmptyLessonAndAssignment: "Không có bài học và bài tập nào",
                    GradeNow: "Chấm ngay",
                    Submitted: "Đã nộp",
                    Graded: "Đã chấm",
                    NotSubmitted: "Chưa nộp",
                    DraftGrading: "Chấm nháp",
                    DoingAssignment: "Đang làm",
                    ResubmissionRequested: "Yêu cầu nộp lại",
                    DueDate: "Hạn nộp",
                    ViewGradebook: "Xem sổ điểm",
                    ReviewGraded: "Xem lại bài chấm",
                    Completed: "Đã hoàn thành",
                    InProgress: "Đang học",
                    ViewProgress: "Xem tiến độ",
                    ASSIGNMENT: "BÀI TẬP",
                    Assignment: "Bài tập",
                    LESSON: "BÀI HỌC",
                    Chapter: "Chương",
                    Grade: "Khối",
                    ContentLibrary: 'Kho nội dung',
                    ListSubjects: "Danh sách môn học",
                    ViewDetail: "Xem chi tiết",
                    Delete: "Xóa",
                    Instructions: "Hướng dẫn",
                    Decriptions: "Mô tả",
                    Create: "Tạo",
                    Close: "Đóng",
                    ChooseWeek: "Chọn tuần học",
                    Title: "Tiêu đề",
                    ChooseContent: "Chọn loại",
                    ListClassAssigned: "Các lớp học đã giao",
                    Update: "Cập nhật",
                    EditContent: "Sửa nội dung",
                    TotalScore: "Tổng điểm",
                    Assigned: "Giao bài",
                    SaveAssignment: "Lưu bài tập",
                    AssignAssignment: "Giao bài tập",
                    Time: "Thời gian",
                    ChooseClassToAssign: "Chọn lớp để giao",
                    ChooseStudentToAssign: "Chọn học sinh để giao",
                    SelectAll: "Chọn tất cả",
                    Selected: "Đã chọn",
                    ExpirationDate: "Ngày hết hạn",
                    ExpirationTime: "Giờ hết hạn",
                    AddNewSection: "Thêm phần mới",
                    DragOrSelectAComponentFromTheLibraryToGetStarted: "Kéo hoặc chọn thành phần từ thư viện để bắt đầu",
                    DropQuestionHere: "Thả câu hỏi vào đây",
                    Question: "Câu",
                    Total: "Tổng",
                    NoAnswer: "Chưa có đáp án",
                    QuestionLibrary: "Thư viện câu hỏi",
                    InteractiveQuiz: "Câu hỏi tương tác (Quiz)",
                    EssayAndPracticeQuestions: "Câu hỏi tự luận & thực hành",
                    Preview: "Xem trước",
                    SortNumber: "Cập nhật STT",
                    Attribute: "Thuộc tính",
                    GradingMethod: "Cách chấm",
                    QuestionContent: "Nội dung",
                    Answer: "Đáp án",
                    Advanced: "Nâng cao",
                    MoreAnswer: "Thêm lựa chọn",
                    Correct: "Đúng",
                    Incorrect: "Sai",
                    Structure: "Cấu trúc: [Văn bản] [Ô trống 1] [Văn bản]...",
                    TextContent: "Nội dung văn bản",
                    CorrectAnswer: "Đáp án đúng",
                    AddText: "Thêm Văn bản",
                    AddBlank: "Thêm Ô trống",
                    Column: "Cột",
                    Similar: "Tương ứng",
                    AddPair: "Thêm cặp",
                    NoAnswerConfig: "Loại câu hỏi này không có cấu hình đáp án. Điểm sẽ được chấm thủ công",
                    MaxCharacters: "Kí tự tối đa",
                    Auto: "Tự động",
                    Manual: "Chấm tay",
                    Step: "Bước",
                    PasteQuestionJSON: "Dán JSON câu hỏi",
                    PasteQuestionJSONIn: "Dán JSON câu hỏi vào đây...",
                    ViewSampleJSON: "Xem format JSON mẫu",
                    JSONError: "Lỗi JSON",
                    ValidJSON: "JSON hợp lệ",
                    Found: "Tìm thấy",
                    PreviewResult: "Xem trước kết quả",
                    Valid: "hợp lệ",
                    Error: "lỗi",
                    DeleteAll: "Xóa tất cả",
                    Cancel: "Hủy",
                    Explanation: "Có giải thích",
                    Statistics: "Thống kê",
                    LimitAssigned: "Giới hạn nộp bài",
                    OnScaleOf: "trên thang",
                    Refresh: "Làm mới",
                    ViewClassReport: "Xem báo cáo lớp",
                    GradeAllAssignments: "Chấm tất cả bài",
                    FindStudent: "Tìm học sinh",
                    GradeAssignment: "Chấm bài",
                    Actions: "Thao tác",
                    NoticeHighestScoreSubmission: "Chú ý: Hệ thống ghi nhận lần nộp bài được chấm điểm cao nhất",
                    PleaseSelectClassSubjectAssignment: "Vui lòng chọn Lớp, Môn và Bài tập để xem dữ liệu.",
                    MaximumScore: "Điểm tối đa",
                    SubmissionNumber: "Lần nộp",
                    Status: "Trạng thái",
                    SubmissionTime: "Thời gian nộp",
                    Attempt: "Lần",
                    PleaseSelectAssignment: "Vui lòng chọn bài tập",
                    StudentID: "Mã HS",
                    RegistrationNumber: "Số danh bộ",
                    StudentName: "Học sinh",
                    SubmissionInfo: "Thông tin nộp bài",
                    SectionGroupName: "Tên Phần/Nhóm",
                    ShuffleQuestions: "Trộn câu hỏi",
                    ShuffleAnswers: "Trộn đáp án",
                    SectionDescription: "Mô tả/Hướng dẫn cho Phần này",
                    ShowAllQuestionsInGroup: "Hiển thị tất cả câu hỏi trong nhóm",
                    EnterQuestion: "Nhập câu hỏi...",
                    SelectSectionOrQuestionToEdit: "Chọn một phần hoặc câu hỏi để chỉnh sửa.",
                    AssignmentStructure: "Cấu trúc bài tập",
                    GradingProgress: "Tiến độ chấm",
                    SummaryAndGeneralComments: "Tổng kết & Nhận xét chung",
                    FinalScore: "Điểm tổng kết",
                    OverallComment: "Nhận xét chung cho toàn bài",
                    EnterGeneralFeedback: "Nhập nhận xét tổng quát về bài làm của học sinh...",
                    PathNotFound: "Không tìm thấy đường dẫn",
                    TeacherCommentOptional: "Nhận xét của giáo viên (tùy chọn)",
                    SaveDraft: "Lưu nháp",
                    SaveAndPublish: "Lưu và xuất bản",
                    SaveAndAssign: "Lưu và giao bài",
                    PleaseEnterDateTime: "Vui lòng nhập ngày giờ",
                    PleaseSelectAtLeastOneClass: "Vui lòng chọn ít nhất 1 lớp để giao bài!",
                    SaveAndAssignSuccess: "Lưu bài và giao bài thành công!",
                    ClassList: "Danh sách lớp",
                    StartAddingContent: "Bắt đầu thêm nội dung cho bài giảng của bạn từ thư viện bên trái.",
                    NoVideo: "Chưa có video",
                    TextBlock: "Đoạn văn bản",
                    Image: "Hình ảnh",
                    Attachment: "Tệp đính kèm",
                    UnknownComponent: "Thành phần không xác định",
                    TextTitle: "Tiêu đề đoạn văn bản",
                    NewTextContent: "Nội dung văn bản mới",
                    ImageTitle: "Tiêu đề hình ảnh",
                    YoutubeTitle: "Tiêu đề youtube",
                    FileTitle: "Tiêu đề file",
                    Audio: "Audio (Ghi âm/Tải lên)",
                    AudioTitle: "Tiêu đề audio",
                    HtmlTitle: "Tiêu đề HTML",
                    GeneralInfo: "Thông tin chung",
                    Content: "Nội dung",
                    LessonTitle: "Tiêu đề bài giảng",
                    DescriptionGuide: "Mô tả / Hướng dẫn",
                    Week: "Tuần",
                    WeekExample: "Ví dụ: Tuần 5, Ôn tập",
                    ChapterTopic: "Chương / Chủ đề",
                    ChapterExample: "Ví dụ: Chương 1: Lũy thừa",
                    SelectComponentToEdit: "Chọn một thành phần để chỉnh sửa.",
                    BlockTitleOptional: "Tiêu đề khối nội dung (Tùy chọn)",
                    EditText: "Soạn thảo văn bản",
                    UploadImage: "Tải ảnh",
                    Caption: "Chú thích",
                    PasteVideoLink: "Dán link video hoặc youtube...",
                    VideoNote: "*Lưu ý: Tải Video phải dưới 15p và tên file không được vượt quá 100 kí tự",
                    RecordOrUploadAudio: "Ghi âm hoặc tải lên file Audio",
                    ImportFromLibrary: "Import từ kho học liệu",
                    PasteHTML: "Nhập/Dán HTML...",
                    AnswerConfig: "Cấu hình đáp án:",
                    AdvancedAnswerSettings: "Thiếp lập đáp án nâng cao",
                    QuestionContentLabel: "Nội dung câu hỏi:",
                    AddOption: "Thêm lựa chọn",
                    Structure: "Cấu trúc: [Văn bản] [Ô trống 1] [Văn bản]...",
                    ColumnA: "Cột A",
                    ColumnB: "Cột B (tương ứng)",
                    LoadingData: "Đang tải dữ liệu...",
                    ContinuingUpload: "Đang tiếp tục tải lên...",
                    Uploading: "Đang upload...",
                    UpdatingVideoPlaylist: "Đang cập nhật video vào danh sách phát....",
                    WaitingYoutube: "Đang chờ youtube xử lý (có thể mất 2 - 5p)...",
                    VideoStatusError: "Lỗi khi kiểm tra trạng thái xử lý video",
                    VideoTooLongWarning: "Video có thể quá dài (chỉ upload < 15 phút)",
                    SearchingFolder: "Đang tìm kiếm folder...",
                    GrantingFilePermission: "Đang cấp quyền file...",
                    NewOption: "Lựa chọn mới",
                    UploadFile: "Tải file",
                    UploadVideo: "Tải video",
                    ImportDigitalLesson: "Import bài học từ học liệu số",
                    ContentList: "Danh sách nội dung",
                    ContentName: "Tên nội dung",
                    ContentType: "Loại nội dung",
                    Actions: "Thao tác",
                    Thumbnail: "Ảnh bìa",
                    MaterialName: "Tên học liệu",
                    PreviewLesson: "Xem trước bài học",
                    ClickTo: "Bấm",
                    EditContentShort: "để soạn nội dung",
                    ContentHtmlLatex: "Nội dung (hỗ trợ HTML và LaTeX)",
                    NoContent: "Không có nội dung...",
                    Save: "Lưu",
                    LoadingGradebookData: "Đang tải dữ liệu sổ điểm...",
                    ClassGradebook: "Sổ điểm lớp học",
                    FullName: "Họ tên",
                    Maximum: "Tối đa",
                    SelectClassSubjectNotice: "Vui lòng chọn Lớp và Môn học để xem dữ liệu.",
                    ClassAverageScore: "Điểm TB Lớp",
                    PublicContentLibrary: "Kho nội dung công khai",
                    Lesson: "Bài học",
                    RetrieveContent: "Lấy nội dung",
                    ContentRetrieved: "Đã lấy nội dung",
                    NotRetrieved: "Chưa lấy",
                    Creator: "Người tạo",
                    PreviewContent: "Xem trước nội dung",
                    PreviewDraftLesson: "Xem trước bài soạn",
                    RetrievedSuccess: "Lấy nội dung thành công!",
                    Statistical: "Thống kê",
                    HomeworkGiver: "Người giao bài",
                    Classname: "Tên lớp"
                }
            }
        }
    })
    app.use(i18n);
    
    // ✅ Register global directives
    app.directive('auto-table-height', autoTableHeightDirective)
    
    // ✅ Provide global refs
    app.provide('iframeRef', { value: null })
    app.provide('snackbarRef', { value: null })


    vueData.v_Set.themeStyle = {
        theme: {
            options: { customProperties: true },
            themes: {
                light: {
                    dark: false,
                    colors: {
                        primary: "#217D46",
                        secondary: "#5BB377",
                        // background: "#961212",
                        // surface: "#f2f2f2",
                    }
                },
            },
        },
        locale: {
            locale: 'vi',
            fallback: 'en',
            messages
        },
        defaults: {
            global: {
                ripple: false,
                flat: true
            },
            VToolbar: {
                color: "primary",
                density: "compact",
            },
            VTextField: {
                density: "compact",
                clearable: true,
                color: 'primary',
                variant: "outlined",
                hideDetails: "auto",
            },
            VAutocomplete: {
                density: "compact",
                clearable: true,
                color: 'primary',
                hideDetails: "auto",
                variant: "outlined",
                noDataText: "Chưa có dữ liệu"
            },
            VSelect: {
                density: "compact",
                color: 'primary',
                variant: "outlined",
                hideDetails: "auto",
                noDataText: "Chưa có dữ liệu"
            },
            VSwitch: {
                density: "compact",
                color: 'primary',
                hideDetails: "auto",
            },
            VRadioGroup: {
                color: 'primary',
                hideDetails: "auto",
            },
            VCheckbox: {
                density: "compact",
                color: "primary",
                hideDetails: "auto",
                class: "mt-0"
            },
            VList: {
                density: "compact",
                VListSubheader: {
                    style: "padding-inline-start: calc(8px + var(--indent-padding)) !important;"
                },
                VListItem: {
                    style: "padding-inline: 8px",
                    density: "compact",
                }
            },
            VTabs: {
                color: 'primary',
                sliderColor: 'primary',
                density: 'compact',
            },
            VTab: {
                color: 'primary',
                density: 'compact',
            },
            VTabsWindowItem: {
                transition: true
            },
            VProgressCircular: {
                color: 'primary'
            },
            VAvatar: {
                color: '',
            },
            VDataTable: {
                density: "compact",
                loadingText: "Đang tải dữ liệu...",
                noDataText: "Chưa có dữ liệu",
                itemsPerPageText: 'Dữ liệu trên mỗi trang',
                pageText: "{0}-{1} trên {2}",
                itemsPerPage: 10,
                itemsPerPageOptions: [
                    { value: 10, title: '10' },
                    { value: 15, title: '15' },
                    { value: 25, title: '25' },
                    { value: 50, title: '50' },
                    { value: 100, title: '100' },
                    { value: -1, title: 'Tất cả' }
                ],
                showCurrentPage: true,
                hover: true,
                fixedHeader: true,
                sticky: true,
                VProgressLinear: {
                    color: 'primary'
                }
            },
            VDataTableVirtual: {
                density: "compact",
                loadingText: "Đang tải dữ liệu...",
                noDataText: "Chưa có dữ liệu",
                itemsPerPageText: 'Dữ liệu trên mỗi trang',
                pageText: "{0}-{1} trên {2}",
                itemsPerPage: 10,
                itemsPerPageOptions: [
                    { value: 10, title: '10' },
                    { value: 15, title: '15' },
                    { value: 25, title: '25' },
                    { value: 50, title: '50' },
                    { value: 100, title: '100' },
                    { value: -1, title: 'Tất cả' }
                ],
                showCurrentPage: true,
                hover: true,
                fixedHeader: true,
                sticky: true,
                VProgressLinear: {
                    color: 'primary'
                },
            },
            VFileInput: {
                density: "compact",
                color: 'primary',
                variant: "outlined",
                hideDetails: "auto",
            },
            VCard: {
                VCardTitle: {
                    class: 'd-flex align-center ga-2 px-2 py-1 text-primary',
                    style: "font-size: 1rem"
                },
                VCardText: {
                    style: "padding: 0 8px 6px"
                }
            },
            VDialog: {
                zIndex: 1006,
            },
            VExpansionPanels: {
                variant: 'accordion'
            },
            VBtn: {              // ← sửa từ VButton
                variant: "outlined",
                // color: "primary",
                size: "small"
            },
            VChip: {
                size: "small",
                label: true,
                density: "comfortable",
            },
            VAlert: {
                density: "compact",
                variant: "tonal",
            },
            VContainer: {
                class: "pa-0 w-100",
                style: "max-width: 100% !important;"
            },
            VRow: {
                dense: true
            },
            VAppBar: {
                density:"compact"
            }
        }
    }
})
